export const forkMe: string;
export const logos: string;
export const react: string;
export const redux: string;
export const typescript: string;
export const webpack: string;
export const header: string;
export const navbar: string;
export const container: string;
